import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Outfit } from "next/font/google";
import "./globals.css";

import ContextProvider from "@/context/userContext";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "./_components/app-sidebar";
import AppHeading from "./_components/app-heading";
import AlertDialogOverlay from "./_components/alertDialogOverlay";
import FolderProvider from "@/context/folderContext";
import EventsProvider from "@/context/eventsContext";
import NotesProvider from "@/context/notesContext";
import Overlay from "./_components/overlay";
import ClientWrapper from "./_components/clientWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        className={`${outfit.variable} ${geistMono.variable} text-gray-800 overflow-y-scroll  bg-gray-300 antialiased`}
      >
        <ContextProvider>
          <FolderProvider>
            <NotesProvider>
              <EventsProvider>
              <ClientWrapper>{children}</ClientWrapper> {/* Use wrapper */}
              </EventsProvider>
            </NotesProvider>
          </FolderProvider>
        </ContextProvider>
      </body>
    </html>
  );
}