import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Outfit } from "next/font/google";
import "./globals.css";
import HomeLayout from "./_components/MainLayout";
import ContextProvider from "@/context/userContext";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { AppSidebar } from "./_components/app-sidebar";
import AppHeading from "./_components/app-heading";
import AlertDialogOverlay from "./_components/alertDialogOverlay";
import FolderProvider from "@/context/folderContext";
import EventsProvider from "@/context/eventsContext";
import NotesProvider from "@/context/notesContext";
import Overlay from "./_components/overlay";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"]
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${outfit.variable} ${geistMono.variable} text-gray-800 overflow-hidden bg-gray-300 antialiased`}
      >
        <ContextProvider>
          <FolderProvider>
            <NotesProvider>
              <EventsProvider>
              <SidebarProvider>
            <AppSidebar   />
            <main className="w-full h-screen m-4 flex flex-col gap-4">
             <div className="flex gap-4 bg-slate-50 p-4 rounded-xl">
             <SidebarTrigger className="text-black" />
             <AppHeading />
             </div>
             <div className=" h-[calc(100%-7rem)] bg-slate-50 p-4 
            overflow-y-scroll rounded-xl" >
               {children}
             </div>
             <AlertDialogOverlay />
             <Overlay />
            </main>
          </SidebarProvider>
              </EventsProvider>
       
            </NotesProvider>
         
          </FolderProvider>
          
        </ContextProvider>
    
        
       
       
      
      </body>
    </html>
  );
}
  // <HomeLayout>{children}</HomeLayout>